### ISSUE TITLE
Jump to the searched symbol is not working

### ISSUE THREAD

**Issue by sidhuhere** [JoeyLu93/vscode-fuzzy-tag#3]
When we press enter to jump to the listed symbol after search, the jump is not working. It just returns without going to the specific file.

**Comment by JoeyLu93** [comment]
An other issue also mentioned that jumping cannot work on mac OS. Are you working on mac, too?
Maybe we can find some errors in developer model.

**Comment by joeylueasy** [comment]
I have fixed a jump bug caused by path parsing. You can update the plug-in and try again.

**Comment by sidhuhere** [comment]
Yes I am working on Mac. Still the jump is not working. Sorry for late reply.

**Comment by sidhuhere** [comment]
After reloading works fine. Thanks for the update,
